[#ftl/]
[@b.textfield name="makeupTaker.std.user.code" label="学号"/]
[@b.textfield name="makeupTaker.std.user.name" label="姓名"/]
[@b.textfield name="makeupTaker.std.state.grade" label="年级"/]
[@b.select name="makeupTaker.std.state.department.id" label="部门" items=departmentList empty="..."/]
[@b.textfield name="makeupTaker.std.state.squad.name" label="班级"/]
[@b.textfield name="makeupTaker.makeupCourse.crn" label="课程序号"/]
[@b.textfield name="makeupTaker.makeupCourse.course.code" label="课程代码"/]
[@b.textfield name="makeupTaker.makeupCourse.course.name" label="课程名称"/]
